Refinements to auditing of active projects to apply more optimal offsets per Nextcloud housekeeping operations
Miscellaneous optimizations and reorganization of auditing scripts

Enhancements to auditing automated tests

diff --git a/utils/admin/audit-active-projects b/utils/admin/audit-active-projects
--- a/utils/admin/audit-active-projects
+++ b/utils/admin/audit-active-projects
@@ -31,13 +31,16 @@
 SCRIPT=`basename "$(realpath $0)"`
 
 USAGE="
-Usage: $SCRIPT [ ( date[time] | week | month | year ) ] [ ( --staging | --frozen ) ] [ --timestamps ] [ ( --report | --report-errors ) [ email ] ]
+Usage: $SCRIPT [ ( after | days-after |  'week' | 'month' | 'year' ) [ before | days-before ]] [ [ ( --staging | --frozen ) ] [ --timestamps ] [ ( --report | --report-errors ) [ email ] ]
        $SCRIPT -h
 
-       date[time]       auditing will be limted to projects active the specified date[time]
-       week             auditing will be limted to projects active during the past week
-       month            auditing will be limted to projects active during the past month
-       year             auditing will be limted to projects active during the past year
+       after            auditing will be limted to project data changes after the specified date[time] (defaults to 10 days)
+       before           auditing will be limted to project data changes before the specified date[time] (defaults to 3 days)
+       days-after       auditing will be limted to project data changes after the past number of days specified
+       days-before      auditing will be limted to project data changes before the past number of days specified
+       week             auditing will be limted to project data changes during the past week
+       month            auditing will be limted to project data changes during the past month
+       year             auditing will be limted to project data changes during the past year
        --staging        auditing will be limited to files in the staging area
        --frozen         auditing will be limited to files in the frozen area
        --timestamps     comparisons will be made between disk timestamps and database values
@@ -45,15 +48,13 @@ Usage: $SCRIPT [ ( date[time] | week | month | year ) ] [ ( --staging | --frozen
        --report-errors  auditing results will be emailed, but only if errors are detected
        email            the email address where audit reports should be sent (defaults to configured recipient list)
 
-If no active time period is specified, a period corresponding to the past 24 hours is used by default.
+Auditing will be limited to projects with data changes during the specified or default period of activity.
 
-Auditing will be limited to files uploaded or frozen during specified or default period of activity, and
-their ancestor folders.
+It is expected that this script will be executed via a cron job once per week, using the defaults, which will result
+in regular auditing of all project data changes in 7 day increments, offset by 3 days from the time of execution.
 "
 
 PROJECT="null"
-SINCE=""
-AUDIT_ARGS=""
 
 # --------------------------------------------------------------------------------
 # Initialize script with common definitions
@@ -71,21 +72,38 @@ fi
 # --------------------------------------------------------------------------------
 # Process command line options
 
-if [ $# -gt 0 ]; then
+if [ "$1" ]; then
     case "$1" in
         "--staging" | "--frozen" | "--timestamps" | "--report" | "--report-errors" )
             AUDIT_ARGS="$*"
             ;;
         *)
             if [[ "$1" =~ ^(week|month|year)$ ]]; then
-                SINCE=`date -d "$START - 1 $1" +"%Y-%m-%dT%H:%M:%SZ"`
+                AFTER=`date -d "$START - 1 $1" +"%Y-%m-%dT%H:%M:%SZ"`
+            elif [[ "$1" =~ ^[[:digit:]][[:digit:]]*$ ]]; then
+                AFTER=`date -d "$START - $1 days" +"%Y-%m-%dT%H:%M:%SZ"`
             elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
-                SINCE="$1"
+                AFTER="$1"
             elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
-                SINCE="$1""T00:00:00Z"
+                AFTER="$1""T00:00:00Z"
             else
-                echo "Invalid date[time]: $SINCE"
+                echo "Invalid after parameter: $1"
                 exit 1
+            fi
+            if [ "$2" ]; then
+                if [[ "$2" =~ ^[[:digit:]][[:digit:]]*$ ]]; then
+                    BEFORE=`date -d "$START - $2 days" +"%Y-%m-%dT%H:%M:%SZ"`
+                    shift
+                elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
+                    BEFORE="$2"
+                    shift
+                elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
+                    BEFORE="$2""T00:00:00Z"
+                    shift
+                else
+                    echo "Invalid before parameter: $2"
+                    exit 1
+                fi
             fi
             shift
             AUDIT_ARGS="$*"
@@ -93,32 +111,51 @@ if [ $# -gt 0 ]; then
     esac
 fi
 
-# If date(time) not specified, calculate datetime for 24 hours ago.
-if [ "$SINCE" = "" ]; then
-    SINCE=`date -d "$START - 24 hours" +"%Y-%m-%dT%H:%M:%SZ"`
+# Set defaults if not defined elsewhere, allowing the configuration or environment to override defaults
+
+if [ "$AFTER" = "" ]; then
+    if [ "AUDIT_ACTIVE_DAYS_AFTER" ]; then
+        AFTER=`date -d "$START - $AUDIT_ACTIVE_DAYS_AFTER days" +"%Y-%m-%dT%H:%M:%SZ"`
+    else
+        AFTER=`date -d "$START - 10 days" +"%Y-%m-%dT%H:%M:%SZ"`
+    fi
 fi
 
-AUDIT_ARGS="--changed-since $SINCE $AUDIT_ARGS"
+if [ "$BEFORE" = "" ]; then
+    if [ "AUDIT_ACTIVE_DAYS_BEFORE" ]; then
+        BEFORE=`date -d "$START - $AUDIT_ACTIVE_DAYS_BEFORE days" +"%Y-%m-%dT%H:%M:%SZ"`
+    else
+        BEFORE=`date -d "$START - 3 days" +"%Y-%m-%dT%H:%M:%SZ"`
+    fi
+fi
+
+AUDIT_ARGS="--changed-after $AFTER --changed-before $BEFORE $AUDIT_ARGS"
+
+if [ "$DEBUG" = "true" ]; then
+    echo "AUDIT_ARGS: $AUDIT_ARGS"
+fi
 
 # --------------------------------------------------------------------------------
 
-PROJECTS=`$ROOT/utils/admin/list-active-projects $SINCE`
+PROJECTS=`DEBUG=false $ROOT/utils/admin/list-active-projects $AFTER $BEFORE 2>/dev/null`
 
 INTERNAL_PROJECTS=""
 
 if [ "$IDA_ENVIRONMENT" = "PRODUCTION" ]; then
-    INTERNAL_PROJECTS=`$ROOT/utils/admin/list-internal-projects | tr '\n' ' '`
+    INTERNAL_PROJECTS=`DEBUG=false $ROOT/utils/admin/list-internal-projects | tr '\n' ' ' 2>/dev/null`
 fi
 
 if [ "$DEBUG" = "true" ]; then
-    echo "AUDIT_ARGS: $AUDIT_ARGS"
-    echo "INTERNAL:   $INTERNAL_PROJECTS"
+    echo "INTERNAL: $INTERNAL_PROJECTS"
 fi
 
 for PROJECT in $PROJECTS; do
     INTERNAL=`echo " $INTERNAL_PROJECTS " | grep " $PROJECT "`
     if [ "$INTERNAL" = "" ]; then
-        $ROOT/utils/admin/audit-project $PROJECT $AUDIT_ARGS
+        if [ "$DEBUG" = "true" ]; then
+            echo "PROJECT: $PROJECT"
+        fi
+        DEBUG=false $ROOT/utils/admin/audit-project $PROJECT $AUDIT_ARGS 2>/dev/null
     fi
 done
 
diff --git a/utils/admin/audit-project b/utils/admin/audit-project
--- a/utils/admin/audit-project
+++ b/utils/admin/audit-project
@@ -38,7 +38,8 @@ Usage: $SCRIPT project [ OPTIONS ]
        OPTIONS:
 
        --full
-       --changed-since date[time] 
+       --changed-after  date[time] 
+       --changed-before date[time] 
        ( --staging | --frozen ) 
        --timestamps 
        --checksums 
@@ -47,8 +48,9 @@ Usage: $SCRIPT project [ OPTIONS ]
        WHERE:
 
        project          the project to be audited
-       --full           full audit, overrides any options --changed-since --staging --frozen; implies --timestamps --checksums
-       --changed-since  auditing will be limited to files uploaded or frozen since the specified date[time]
+       --full           full audit, implies --timestamps --checksums and none of --changed-* --staging --frozen
+       --changed-after  auditing will be limited to project data changes after the specified date[time]
+       --changed-before auditing will be limited to project data changes after before the specified date[time]
        date[time]       an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/
        --staging        auditing will be limited to files in the staging area
        --frozen         auditing will be limited to files in the frozen area
@@ -58,14 +60,16 @@ Usage: $SCRIPT project [ OPTIONS ]
        --report-errors  auditing results will be emailed, but only if errors are detected
        email            the email address where audit reports should be sent (defaults to configured recipient list)
 
-If --changed-since is specified, files and folders which are outside the scope of files uploaded or frozen
-since the specified datetime, including changes only occurring in the filesystem and not known to Nextcloud,
-will not not be reported; only changes which can be identified by timestamp updates in the Nextcloud or Metax
-databases which are later than the specified since timestamp will be audited. To detect filesystem only changes
-you must perform an unrestricted audit without specifying any --changed-since parameter.
+If --changed-after and/or --changed-before are specified, files and folders which are outside the scope of files
+uploaded or frozen during the specified period, including changes only occurring in the filesystem and not known
+to Nextcloud, will not not be included in the audit; only changes which can be identified by timestamp updates in
+the Nextcloud or Metax databases which are within than the specified time period will be audited. To detect
+filesystem only changes you must perform an unrestricted audit without specifying any --changed-* parameters.
 "
 
 # --------------------------------------------------------------------------------
+
+#START_ENV="$START" # allow start timestamp to be explicitly defined (used by tests)
 
 INIT_FILE=`dirname "$(realpath $0)"`/lib/init_audit_script.sh
 
@@ -80,12 +84,17 @@ fi
 
 SNAIL=`mail --version 2>/dev/null | grep -- 's-nail' 2>/dev/null`
 
+#if [ "$START_ENV" ]; then
+#    START="$START_ENV"
+#fi
+
 #--------------------------------------------------------------------------------
 
 REPORT_REQ=""
 RECIPIENTS=""
 FILE_AREA=""
-SINCE=""
+AFTER=""
+BEFORE=""
 FULL_AUDIT=""
 AUDIT_TIMESTAMPS=""
 AUDIT_CHECKSUMS=""
@@ -96,8 +105,12 @@ while [ "$1" ]; do
 
     case "$1" in
         "--full")
-            if [ "$SINCE" ]; then
-                echo "Only one of --full or --changed-since is allowed"
+            if [ "$AFTER" ]; then
+                echo "Only one of --full or --changed-after is allowed"
+                exit 1
+            fi
+            if [ "$BEFORE" ]; then
+                echo "Only one of --full or --changed-before is allowed"
                 exit 1
             fi
             if [ "$FILE_AREA" ]; then
@@ -107,12 +120,13 @@ while [ "$1" ]; do
             FULL_AUDIT="$1"
             AUDIT_TIMESTAMPS=""
             AUDIT_CHECKSUMS=""
-            SINCE=""
+            AFTER=""
+            BEFORE=""
             FILE_AREA=""
             ;;
-        "--changed-since")
+        "--changed-after")
             if [ "$FULL_AUDIT" ]; then
-                echo "Only one of --full or --changed-since is allowed"
+                echo "Only one of --full or --changed-after is allowed"
                 exit 1
             fi
             if [ "$2" = "" ]; then
@@ -120,9 +134,28 @@ while [ "$1" ]; do
                 exit 1
             fi
             if [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
-                SINCE="$2"
+                AFTER="$2"
             elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
-                SINCE="$2""T00:00:00Z"
+                AFTER="$2""T00:00:00Z"
+            else
+                echo "Invalid date[time]: $2"
+                exit 1
+            fi
+            shift
+            ;;
+        "--changed-before")
+            if [ "$FULL_AUDIT" ]; then
+                echo "Only one of --full or --changed-before is allowed"
+                exit 1
+            fi
+            if [ "$2" = "" ]; then
+                echo "Missing date[time] argument"
+                exit 1
+            fi
+            if [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
+                BEFORE="$2"
+            elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
+                BEFORE="$2""T00:00:00Z"
             else
                 echo "Invalid date[time]: $2"
                 exit 1
@@ -173,9 +206,14 @@ if [ "$REPORT_REQ" != "" ]; then
     fi
 fi
 
-# If date(time) not specified, use the unix epoch
-if [ "$SINCE" = "" ]; then
-    SINCE="1970-01-01T00:00:00Z"
+# If after timestamp not specified, use the unix epoch
+if [ "$AFTER" = "" ]; then
+    AFTER="1970-01-01T00:00:00Z"
+fi
+
+# If before timestamp not specified, use the start time
+if [ "$BEFORE" = "" ]; then
+    BEFORE="$START"
 fi
 
 AUDIT_ARGS="${FULL_AUDIT} ${FILE_AREA} ${AUDIT_TIMESTAMPS} ${AUDIT_CHECKSUMS}"
@@ -185,11 +223,22 @@ AUDIT_ARGS="${FULL_AUDIT} ${FILE_AREA} ${AUDIT_TIMESTAMPS} ${AUDIT_CHECKSUMS}"
 if [ "$DEBUG" = "true" ]; then
     echo "ROOT:       $ROOT"
     echo "PROJECT:    $PROJECT"
+    echo "AFTER:      $AFTER"
+    echo "BEFORE:     $BEFORE"
     echo "START:      $START"
-    echo "SINCE:      $SINCE"
     echo "AUDIT_ARGS: $AUDIT_ARGS"
     echo "REPORT_REQ: $REPORT_REQ"
     echo "RECIPIENTS: $RECIPIENTS"
+fi
+
+if [[ "$AFTER" == "$START" || "$AFTER" > "$START" ]]; then
+    errorExit "Specified after timestamp $AFTER must be in the past"
+fi
+
+if [ "$BEFORE" != "$START" ]; then
+    if [[ "$AFTER" == "$BEFORE" || "$AFTER" > "$BEFORE" ]]; then
+        errorExit "Specified after timestamp $AFTER must be earlier than the specified before timestamp $BEFORE"
+    fi
 fi
 
 #--------------------------------------------------------------------------------
@@ -213,7 +262,7 @@ SUMMARY="$OUTPUT.summary"
 
 source $ROOT/venv/bin/activate
 
-python -u $ROOT/utils/admin/lib/audit_project.py $ROOT $PROJECT $START $SINCE $AUDIT_ARGS > $OUTPUT
+python -u $ROOT/utils/admin/lib/audit_project.py $ROOT $PROJECT $START $AFTER $BEFORE $AUDIT_ARGS > $OUTPUT
 
 if [ $? -ne 0 ]; then
     rm $OUTPUT 2>/dev/null
diff --git a/utils/admin/list-active-projects b/utils/admin/list-active-projects
--- a/utils/admin/list-active-projects
+++ b/utils/admin/list-active-projects
@@ -22,23 +22,27 @@
 # @link     https://research.csc.fi/
 # --------------------------------------------------------------------------------
 #
-# This script scans key database tables to determine which projects have had
-# any activity during the specified period or since the specified date(time),
-# if given, or during the past 24 hours if nothing specified. If only a date
-# is specified, the time T00:00:00Z is used.
+# This script reports which projects have had any project data changes during
+# the specified period, if defined, or during the past 24 hours by default. 
 #
 # --------------------------------------------------------------------------------
 
 SCRIPT=`basename "$(realpath $0)"`
 
 USAGE="
-Usage: $SCRIPT [ ( date[time] | week | month | year ) ] 
+Usage: $SCRIPT [ ( after | days-after | 'week' | 'month' | 'year' ) [ ( before | days-before ) ] ] 
        $SCRIPT -h
 
-       date[time]   an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/ (defaults to 24 hours ago)
-       week         calculate a timestamp one week in the past
-       month        calculate a timestamp one month in the past
-       year         calculate a timestamp one year in the past
+       after        an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/
+       before       an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/
+       days-after   calculate a after timestamp the specified number of days in the past
+       days-before  calculate a before timestamp the specified number of days in the past
+       week         calculate a after timestamp one week in the past
+       month        calculate a after timestamp one month in the past
+       year         calculate a after timestamp one year in the past
+
+If no after time is specified, a period corresponding to the past 24 hours is used by default.
+If an before time is specified, only projects active between the after and before times will be included.
 "
 
 PROJECT="null"
@@ -59,34 +63,75 @@ fi
 #--------------------------------------------------------------------------------
 
 TZ=UTC
-
-SINCE=""
+AFTER=""
+BEFORE=""
 
 if [ "$1" ]; then
+    if [ "$DEBUG" = "true" ]; then
+        echo "ARG 1:  $1"
+    fi
     if [[ "$1" =~ ^(week|month|year)$ ]]; then
-        SINCE=`date -d "$START - 1 $1" +"%Y-%m-%dT%H:%M:%SZ"`
+        AFTER=`date -d "$START - 1 $1" +"%Y-%m-%dT%H:%M:%SZ"`
+    elif [[ "$1" =~ ^[[:digit:]][[:digit:]]*$ ]]; then
+        AFTER=`date -d "$START - $1 days" +"%Y-%m-%dT%H:%M:%SZ"`
     elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
-        SINCE="$1"
+        AFTER="$1"
     elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
-        SINCE="$1""T00:00:00Z"
+        AFTER="$1""T00:00:00Z"
     else
-        echo "Invalid date[time]: $1"
+        echo "Invalid parameter: $1"
         exit 1
+    fi
+
+    if [ "$2" ]; then
+        if [ "$DEBUG" = "true" ]; then
+            echo "ARG 2:  $2"
+        fi
+        if [[ "$2" =~ ^[[:digit:]][[:digit:]]*$ ]]; then
+            BEFORE=`date -d "$START - $2 days" +"%Y-%m-%dT%H:%M:%SZ"`
+        elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
+            BEFORE="$2"
+        elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
+            BEFORE="$2""T00:00:00Z"
+        else
+            echo "Invalid parameter: $2"
+            exit 1
+        fi
     fi
 fi
 
-# If date(time) not specified, calculate datetime for 24 hours ago.
-if [ "$SINCE" = "" ]; then
-    SINCE=`date -d "$START - 24 hours" +"%Y-%m-%dT%H:%M:%SZ"`
+# Set defaults if not defined elsewhere, allowing the configuration or environment to override defaults
+
+if [ "$AFTER" = "" ]; then
+    if [ "$AUDIT_ACTIVE_DAYS_AFTER" ]; then
+        AFTER=`date -d "$START - $AUDIT_ACTIVE_DAYS_AFTER days" +"%Y-%m-%dT%H:%M:%SZ"`
+    else
+        AFTER=`date -d "$START - 1 day" +"%Y-%m-%dT%H:%M:%SZ"`
+    fi
+fi
+
+if [ "$BEFORE" = "" ]; then
+    if [ "$AUDIT_ACTIVE_DAYS_BEFORE" ]; then
+        BEFORE=`date -d "$START - $AUDIT_ACTIVE_DAYS_BEFORE days" +"%Y-%m-%dT%H:%M:%SZ"`
+    else
+        BEFORE="$START"
+    fi
 fi
 
 if [ "$DEBUG" = "true" ]; then
-    echo "SINCE: $SINCE"
-    echo "START: $START"
+    echo "AFTER:  $AFTER"
+    echo "BEFORE: $BEFORE"
+    echo "START:  $START"
 fi
 
-if [[ "$SINCE" > "$START" ]]; then
-    errorExit "Specified timestamp $SINCE is in the future"
+if [[ "$AFTER" == "$START" || "$AFTER" > "$START" ]]; then
+    errorExit "Specified after timestamp $AFTER must be in the past"
+fi
+
+if [ "$BEFORE" != "$START" ]; then
+    if [[ "$AFTER" == "$BEFORE" || "$AFTER" > "$BEFORE" ]]; then
+        errorExit "Specified after timestamp $AFTER must be earlier than the specified before timestamp $BEFORE"
+    fi
 fi
 
 PROJECTS=`DEBUG=false $ROOT/utils/admin/list-projects`
@@ -111,7 +156,7 @@ for PROJECT in $PROJECTS; do
         echo "LAST_CHANGE: $LAST_CHANGE"
     fi
 
-    if [[ "$LAST_CHANGE" > "$SINCE" ]]; then
+    if [[ "$LAST_CHANGE" > "$AFTER" && "$LAST_CHANGE" < "$BEFORE" ]]; then
         echo "${PROJECT}"
     fi
 
