Refinements to admin utility scripts used to send emails

diff --git a/utils/admin/email-project-users b/utils/admin/email-project-users
--- a/utils/admin/email-project-users
+++ b/utils/admin/email-project-users
@@ -30,7 +30,17 @@ SCRIPT=`basename "$(realpath $0)"`
 USAGE="
 Usage: $SCRIPT project subject message
        $SCRIPT -h
+
+The environment variable EMAIL_SENDER must be defined with a valid email address
+
+The environment variable EMAIL_RECIPIENTS may optionally be defined with a comma
+separated list of email addresses
 "
+
+if [ "$1" = "-h" ]; then
+    echo "$USAGE"
+    exit
+fi
 
 #--------------------------------------------------------------------------------
 
@@ -44,11 +54,11 @@ trap cleanup EXIT
 
 #--------------------------------------------------------------------------------
 
-# If there is no email sender configured in the environment, we do nothing
+# If there is no email sender defined in the environment, we do nothing
 
 if [ "$EMAIL_SENDER" = "" ]; then
-    echo "Warning: No email sender configured. Exiting." >&2
-    exit
+    echo "Error: No EMAIL_SENDER environment variable defined. Exiting." >&2
+    exit 1
 fi
 
 #--------------------------------------------------------------------------------
@@ -56,30 +66,34 @@ fi
 PROJECT="$1"
 
 if [ "$PROJECT" = "" ]; then
-    echo "No project specified" >&2
+    echo "Error: No project specified. Exiting." >&2
     exit 1
 fi
 
 SUBJECT="$2"
 
 if [ "$SUBJECT" = "" ]; then
-    echo "No email subject specified" >&2
+    echo "Error: No email subject specified. Exiting." >&2
     exit 1
 fi
 
 MESSAGE="$3"
 
 if [ "$MESSAGE" = "" ]; then
-    echo "No email message specified" >&2
+    echo "Error: No email message specified. Exiting." >&2
     exit 1
 fi
 
-SNAIL=`mail --version 2>/dev/null | grep -- 's-nail'`
+SNAIL=`mail --version 2>/dev/null | grep -- 's-nail' 2>/dev/null`
 
 #--------------------------------------------------------------------------------
 
 SUBJECT=`echo "$2" | tr '\n' ' '`
 SUBJECT="[IDA Service] ${SUBJECT}"
+
+if [ "$IDA_ENVIRONMENT" != "PRODUCTION" ]; then
+    SUBJECT="${IDA_ENVIRONMENT} (${HOSTNAME}) ${SUBJECT}"
+fi
 
 MESSAGE="${MESSAGE}
 
@@ -101,18 +115,7 @@ if [ "$RECIPIENTS" = "" ]; then
     echo "Warning: The project ${PROJECT} has no users!"
 fi
 
-
-if [ -z "$SNAIL" ]; then
-    # If internal recipients are defined in configuration, add internal recipients
-    if [ "$EMAIL_RECIPIENTS" != "" ]; then
-        if [ "$RECIPIENTS" = "" ]; then
-            RECIPIENTS="$EMAIL_RECIPIENTS"
-        else
-            RECIPIENTS="-b $EMAIL_RECIPIENTS $RECIPIENTS"
-        fi
-    fi
-    COMMAND="mail -s \"${SUBJECT}\" -r ${EMAIL_SENDER} -S \"replyto=${EMAIL_SENDER}\" ${RECIPIENTS}"
-else
+if [ "$SNAIL" ]; then
     # Convert comma delimited recipient lists to space delimited
     RECIPIENTS=`echo "$RECIPIENTS" | sed -e 's/,/ /g'`
     # If internal recipients are defined in configuration, add internal recipients
@@ -125,7 +128,17 @@ else
             RECIPIENTS="-b $EMAIL_RECIPIENTS $RECIPIENTS"
         fi
     fi
-    COMMAND="s-nail -s \"${SUBJECT}\" -r ${EMAIL_SENDER} ${RECIPIENTS}"
+    COMMAND="mail -s \"${SUBJECT}\" -r ${EMAIL_SENDER} ${RECIPIENTS}"
+else
+    # If internal recipients are defined in configuration, add internal recipients
+    if [ "$EMAIL_RECIPIENTS" != "" ]; then
+        if [ "$RECIPIENTS" = "" ]; then
+            RECIPIENTS="$EMAIL_RECIPIENTS"
+        else
+            RECIPIENTS="-b $EMAIL_RECIPIENTS $RECIPIENTS"
+        fi
+    fi
+    COMMAND="mail -s \"${SUBJECT}\" -r ${EMAIL_SENDER} -S \"replyto=${EMAIL_SENDER}\" ${RECIPIENTS}"
 fi
 
 if [ "$DEBUG" = "true" ]; then
