Refinements to email messages sent to users when suspending or deleting a project.

diff --git a/utils/admin/fetch-project-emails b/utils/admin/fetch-project-emails
--- a/utils/admin/fetch-project-emails
+++ b/utils/admin/fetch-project-emails
@@ -35,6 +35,13 @@ fi
 
 #--------------------------------------------------------------------------------
 
+if [ "$LDAP_HOST_URL" = "" ]; then
+    echo "No LDAP connection configured. Aborting." >&2
+    exit 1
+fi
+
+#--------------------------------------------------------------------------------
+
 export LDAP_HOST_URL
 export LDAP_BIND_USER
 export LDAP_PASSWORD
