Refactored checks for non-production (test) environment to check instead for production environment so that the same behavior exists for both test and demo environments

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -79,8 +79,8 @@ fi
 #--------------------------------------------------------------------------------
 # Verify that we are in a test environment
 
-if [ "$IDA_ENVIRONMENT" != "TEST" ]; then
-    echo "This script can only be run in a test environment. Aborting." >&2
+if [ "$IDA_ENVIRONMENT" == "PRODUCTION" ]; then
+    echo "This script can not be run in a production environment. Aborting." >&2
     exit 1
 fi
 
