Added new option --checksums to audit-project script, causing generation of new checksum for all files on disk and comparison of new checksum and all defined checksums in Nextcloud cache, IDA, and Metax
Added new option --full to audit-project script, causing a full audit, including timestamps and checksums and ignoring any other specified restrictions with --changed-since --staging --frozen

Created new utility generate-missing-checksums which will generate and save Nextcloud file cache checksums for all files on disk which do not have a cache checksum defined (expected to be run as a nightly cron job)

Created new repair utility script repair-checksums, resolving all checksum errors detailed in an audit report

Refactoring and optimizations of audit report output, auditing process, and automated tests

Updated metadata publication agent to compare existing cache checksums with those generated during postprocessing and fail the action if any checksum mismatches are detected (presuming file corruption has occurred since upload)

Updated the repair-project script to take either a project name or audit error report, and if a report is specified, execute repair-timestamps and repair-checksums as part of the process

Added generation of missing cache checksums to test project initialization

Refinements to list-active-projects and audit-active-projects scripts

General refinements, normalization, and optimizations of admin utility scripts, configuration loading, and logging

Bumped gevent version to 23.9.1 per https://github.com/CSCfi/fairdata-ida/security/dependabot/25

diff --git a/tests/utils/initialize-test-accounts b/tests/utils/initialize-test-accounts
--- a/tests/utils/initialize-test-accounts
+++ b/tests/utils/initialize-test-accounts
@@ -385,7 +385,7 @@ for PROJECT in $PROJECTS; do
         success
     fi
 
-    # Update Nextcloud uploaded timestamp for all test account files to current datetime
+    # Update Nextcloud uploaded timestamp to current datetime and generate cache checksum for all test account files
 
     PGPASSWORD="$DBPASSWORD"
     export PGPASSWORD
@@ -443,8 +443,15 @@ for PROJECT in $PROJECTS; do
             echo "Error: Failed to update Nextcloud upload timestamp for file $FILEID for $USER: $OUT"
             exit 1
         fi
-
     done
+
+    OUT=$($ROOT/utils/admin/generate-missing-checksums $PROJECT 2>&1)
+
+    if [ "$?" -ne 0 ]; then
+        failure "failed"
+        echo "Error: Failed to generate cache checksums for project $PROJECT"
+        exit 1
+    fi
 
 done
 
@@ -508,5 +515,5 @@ FOUND=`echo "$PROJECTS" | grep "test_project_f"`
 
 if [ "$FOUND" ]; then
     echo "Creating failed action in project test_project_f..."
-    $CURL_POST $IDA_CREDENTIALS "${IDA_API_ROOT_URL}/actions?project=test_project_f&pathname=/&action=freeze&error=Boom%21&failed=${TIMESTAMP}" >/dev/null
+    $CURL_POST $IDA_CREDENTIALS "${IDA_API_ROOT_URL}/actions?project=test_project_f&pathname=/&action=freeze&error=Boom%21&failed=${START}" >/dev/null
 fi
diff --git a/utils/admin/repair-checksums b/utils/admin/repair-checksums
--- a/utils/admin/repair-checksums
+++ b/utils/admin/repair-checksums
@@ -2,7 +2,7 @@
 # --------------------------------------------------------------------------------
 # This file is part of the IDA research data storage service
 #
-# Copyright (C) 2019 Ministry of Education and Culture, Finland
+# Copyright (C) 2023 Ministry of Education and Culture, Finland
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published
@@ -21,9 +21,25 @@
 # @license  GNU Affero General Public License, version 3
 # @link     https://research.csc.fi/
 # --------------------------------------------------------------------------------
-# Initialize script with common definitions
+# This script loads a project audit error file (encoded in JSON) and for each
+# checksum error will update the checksums in Nextcloud, IDA, and Metax as
+# appropriate, ensuring they match the timestamp generated by the auditing
+# process which produced the report.
+# --------------------------------------------------------------------------------
 
-INIT_FILE=`dirname $0`/lib/init_admin_script.sh
+SCRIPT=`basename "$(realpath $0)"`
+PROJECT="null"
+
+USAGE="
+Usage: $SCRIPT error_file
+       $SCRIPT -h
+
+       error_file  the pathname of the audit error file to be loaded
+"
+
+#--------------------------------------------------------------------------------
+
+INIT_FILE=`dirname "$(realpath $0)"`/lib/init_audit_script.sh
 
 if [ -e $INIT_FILE ]
 then
@@ -35,17 +51,24 @@ fi
 
 #--------------------------------------------------------------------------------
 
-if [ "$LDAP_HOST_URL" = "" ]; then
-    errorExit "No LDAP connection configured!"
+ERROR_FILE="$1"
+
+if [ -z "$ERROR_FILE" ]; then
+    echo "Error: no input file pathname specified"
+    echo "$USAGE"
+    exit 1
+fi
+
+if [ ! -f "$ERROR_FILE" ]; then
+    echo "Error: the specified input file does not exist"
+    echo "$USAGE"
+    exit 1
 fi
 
 #--------------------------------------------------------------------------------
 
-export LDAP_HOST_URL
-export LDAP_BIND_USER
-export LDAP_PASSWORD
-export LDAP_SEARCH_BASE
+source $ROOT/venv/bin/activate
 
-$ROOT/utils/admin/lib/fetch_project_emails.pl $PROJECT | tr '\n' ',' | sed -e 's/,$//'
+python -u $ROOT/utils/admin/lib/repair_checksums.py $ROOT "$ERROR_FILE"
 
 addToLog "DONE"
