Added support for a new --changed-since <date\[time\]> parameter to the audit-project admin script which will limit audits to files which have been uploaded, frozen, or modified since the specified date\[time\], and their ancestor folders
Merged the functionality of the analyze-audit-errors admin utility script into the audit-project script and report output

Renamed the --check-timestamps auditing parameter to --timestamps

Updated the list-active-projects admin utility to check upload timestamps

diff --git a/tests/utils/initialize-test-accounts b/tests/utils/initialize-test-accounts
--- a/tests/utils/initialize-test-accounts
+++ b/tests/utils/initialize-test-accounts
@@ -119,6 +119,10 @@ else
     EXTRA_RELATIONS="test_user_x:test_project_b test_user_x:test_project_c test_user_x:test_project_d test_user_x:test_project_e"
 fi
 
+if [ "$STAGING_FOLDER_SUFFIX" = "" ]; then
+    errorExit "Error: The STAGING_FOLDER_SUFFIX must be defined"
+fi
+
 #--------------------------------------------------------------------------------
 
 PADDING="-45"
@@ -339,10 +343,6 @@ for PROJECT in $PROJECTS; do
     STEP="   Initializing data for $PROJECT"
     printf "%${PADDING}s" "$STEP"
 
-    if [ "$STAGING_FOLDER_SUFFIX" = "" ]; then
-        errorExit "Error: The STAGING_FOLDER_SUFFIX must be defined"
-    fi
-
     USER="$PROJECT_USER_PREFIX""$PROJECT"
     PROJECT_STAGING_FOLDER="$PROJECT$STAGING_FOLDER_SUFFIX"
     PROJECT_FROZEN_FOLDER="$PROJECT"
@@ -384,6 +384,67 @@ for PROJECT in $PROJECTS; do
     else
         success
     fi
+
+    # Update Nextcloud uploaded timestamp for all test account files to current datetime
+
+    PGPASSWORD="$DBPASSWORD"
+    export PGPASSWORD
+
+    NOW=`date -u +'%s'`
+
+    QUERY="SELECT numeric_id FROM ${DBTABLEPREFIX}storages WHERE id = 'home::${USER}' ORDER BY numeric_id DESC LIMIT 1"
+
+    OUT=$(psql -h "$DBHOST" -p "$DBPORT" -d "$DBNAME" -U "$DBUSER" -c "$QUERY" -t 2>&1)
+
+    if [ "$?" -ne 0 ]; then
+        failure "failed"
+        echo "Error: Failed to retrieve Nextcloud storage id for $USER: $OUT"
+        exit 1
+    fi
+
+    STORAGE=$(echo "$OUT" | sed -e 's/[^0-9]//g')
+
+    if [ -z "$STORAGE" ]; then
+        failure "failed"
+        echo "Error: Failed to retrieve Nextcloud storage id for $USER"
+        exit 1
+    fi
+
+    QUERY="SELECT fileid FROM ${DBTABLEPREFIX}filecache WHERE storage = $STORAGE AND mimetype != 2 AND path ~ '^files/'"
+
+    OUT=$(psql -h "$DBHOST" -p "$DBPORT" -d "$DBNAME" -U "$DBUSER" -c "$QUERY" -t 2>&1)
+
+    if [ "$?" -ne 0 ]; then
+        failure "failed"
+        echo "Error: Failed to retrieve Nextcloud file ids for $USER: $OUT"
+        exit 1
+    fi
+
+    FILEIDS=$(echo "$OUT" | sed -e 's/[^0-9][^0-9]*/ /g' | sed -e 's/^  *//' | sed -e 's/  *$//')
+
+    if [ -z "$FILEIDS" ]; then
+        failure "failed"
+        echo "Error: Failed to retrieve Nextcloud file ids for $USER"
+        exit 1
+    fi
+
+    for FILEID in $FILEIDS; do
+
+        QUERY="INSERT INTO ${DBTABLEPREFIX}filecache_extended \
+              (fileid, metadata_etag, creation_time, upload_time) \
+              VALUES ($FILEID, null, 0, $NOW) \
+              ON CONFLICT (fileid) DO UPDATE \
+              SET upload_time = $NOW"
+
+        OUT=$(psql -h "$DBHOST" -p "$DBPORT" -d "$DBNAME" -U "$DBUSER" -c "$QUERY" 2>&1)
+
+        if [ "$?" -ne 0 ]; then
+            failure "failed"
+            echo "Error: Failed to update Nextcloud upload timestamp for file $FILEID for $USER: $OUT"
+            exit 1
+        fi
+
+    done
 
 done
 
diff --git a/utils/admin/audit-active-projects b/utils/admin/audit-active-projects
--- a/utils/admin/audit-active-projects
+++ b/utils/admin/audit-active-projects
@@ -31,37 +31,29 @@
 SCRIPT=`basename "$(realpath $0)"`
 
 USAGE="
-Usage: $SCRIPT [ ( timestamp | week | month | year ) ] [ ( --staging | --frozen ) ] [ --check-timestamps ] [ ( --report | --report-errors ) [ email ] ]
+Usage: $SCRIPT [ ( date[time] | week | month | year ) ] [ ( --staging | --frozen ) ] [ --timestamps ] [ ( --report | --report-errors ) [ email ] ]
        $SCRIPT -h
 
-       timestamp           an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/ (defaults to 24 hours ago)
-       week                calculate a timestamp one week in the past
-       month               calculate a timestamp one month in the past
-       year                calculate a timestamp one year in the past
-       --staging           auditing will be limited to files in the staging area
-       --frozen            auditing will be limited to files in the frozen area
-       --check-timestamps  comparisons will be made between disk timestamps and database values
-       --report            auditing results will be emailed
-       --report-errors     auditing results will be emailed, but only if errors are detected
-       email               the email address where audit reports should be sent (defaults to dev team)
+       date[time]       auditing will be limted to projects active the specified date[time]
+       week             auditing will be limted to projects active during the past week
+       month            auditing will be limted to projects active during the past month
+       year             auditing will be limted to projects active during the past year
+       --staging        auditing will be limited to files in the staging area
+       --frozen         auditing will be limited to files in the frozen area
+       --timestamps     comparisons will be made between disk timestamps and database values
+       --report         auditing results will be emailed
+       --report-errors  auditing results will be emailed, but only if errors are detected
+       email            the email address where audit reports should be sent (defaults to configured recipient list)
+
+If no active time period is specified, a period corresponding to the past 24 hours is used by default.
+
+Auditing will be limited to files uploaded or frozen during specified or default period of activity, and
+their ancestor folders.
 "
 
 PROJECT="null"
 SINCE=""
 AUDIT_ARGS=""
-
-if [ $# -gt 0 ]; then
-    case "$1" in
-        "--staging" | "--frozen" | "--check-timestamps" | "--report" | "--report-errors" )
-            AUDIT_ARGS="$*"
-            ;;
-        *)
-            SINCE="$1"
-            shift
-            AUDIT_ARGS="$*"
-            ;;
-    esac
-fi
 
 # --------------------------------------------------------------------------------
 # Initialize script with common definitions
@@ -76,9 +68,41 @@ else
     exit 1
 fi
 
-# --------------------------------------------------------------------------------
-
 #DEBUG="true" # TEMP HACK
+
+# --------------------------------------------------------------------------------
+# Process command line options
+
+if [ $# -gt 0 ]; then
+    case "$1" in
+        "--staging" | "--frozen" | "--timestamps" | "--report" | "--report-errors" )
+            AUDIT_ARGS="$*"
+            ;;
+        *)
+            if [[ "$1" =~ ^(week|month|year)$ ]]; then
+                SINCE=`date -d "$START - 1 $1" +"%Y-%m-%dT%H:%M:%SZ"`
+            elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
+                SINCE="$1"
+            elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
+                SINCE="$1""T00:00:00Z"
+            else
+                echo "Invalid date[time]: $SINCE"
+                exit 1
+            fi
+            shift
+            AUDIT_ARGS="$*"
+            ;;
+    esac
+fi
+
+# If date(time) not specified, calculate datetime for 24 hours ago.
+if [ "$SINCE" = "" ]; then
+    SINCE=`date -d "$START - 24 hours" +"%Y-%m-%dT%H:%M:%SZ"`
+fi
+
+AUDIT_ARGS="--changed-since $SINCE $AUDIT_ARGS"
+
+# --------------------------------------------------------------------------------
 
 PROJECTS=`$ROOT/utils/admin/list-active-projects $SINCE`
 
@@ -89,10 +113,11 @@ if [ "$IDA_ENVIRONMENT" = "PRODUCTION" ]; then
 fi
 
 if [ "$DEBUG" = "true" ]; then
-    echo "SINCE:      $SINCE"
     echo "AUDIT_ARGS: $AUDIT_ARGS"
     echo "INTERNAL:   $INTERNAL_PROJECTS"
 fi
+
+exit
 
 for PROJECT in $PROJECTS; do
     INTERNAL=`echo " $INTERNAL_PROJECTS " | grep " $PROJECT "`
diff --git a/utils/admin/audit-project b/utils/admin/audit-project
--- a/utils/admin/audit-project
+++ b/utils/admin/audit-project
@@ -32,16 +32,24 @@
 SCRIPT=`basename "$(realpath $0)"`
 
 USAGE="
-Usage: $SCRIPT project [ ( --staging | --frozen ) ] [ --check-timestamps ] [ ( --report | --report-errors ) [ email ] ]
+Usage: $SCRIPT project [ --changed-since date[time] ] [ ( --staging | --frozen ) ] [ --timestamps ] [ ( --report | --report-errors ) [ email ] ]
        $SCRIPT -h
 
-       project             the project to be audited
-       --staging           auditing will be limited to files in the staging area
-       --frozen            auditing will be limited to files in the frozen area
-       --check-timestamps  comparisons will be made between disk timestamps and database values
-       --report            auditing results will be emailed
-       --report-errors     auditing results will be emailed, but only if errors are detected
-       email               the email address where audit reports should be sent (defaults to dev team)
+       project          the project to be audited
+       --changed-since  auditing will be limited to files uploaded or frozen since the specified date[time]
+       date[time]       an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/
+       --staging        auditing will be limited to files in the staging area
+       --frozen         auditing will be limited to files in the frozen area
+       --timestamps     comparisons will be made between disk timestamps and database values
+       --report         auditing results will be emailed
+       --report-errors  auditing results will be emailed, but only if errors are detected
+       email            the email address where audit reports should be sent (defaults to configured recipient list)
+
+If --changed-since is specified, files and folders which are outside the scope of files uploaded or frozen
+since the specified datetime, including changes only occurring in the filesystem and not known to Nextcloud,
+will not not be reported; only changes which can be identified by timestamp updates in the Nextcloud or Metax
+databases which are later than the specified since timestamp will be audited. To detect filesystem only changes
+you must perform an unrestricted audit without specifying any --changed-since parameter.
 "
 
 # --------------------------------------------------------------------------------
@@ -63,6 +71,7 @@ fi
 REPORT_REQ=""
 RECIPIENTS=""
 FILE_AREA=""
+SINCE=""
 CHECK_TIMESTAMPS=""
 
 shift # got PROJECT from first argument via init_audit_script.sh
@@ -70,6 +79,21 @@ shift # got PROJECT from first argument via init_audit_script.sh
 while [ "$1" ]; do
 
     case "$1" in
+        "--changed-since")
+            if [ "$2" = "" ]; then
+                echo "Missing date[time] argument"
+                exit 1
+            fi
+            if [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
+                SINCE="$2"
+            elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
+                SINCE="$2""T00:00:00Z"
+            else
+                echo "Invalid date[time]: $2"
+                exit 1
+            fi
+            shift
+            ;;
         "--staging" | "--frozen")
             if [ "$FILE_AREA" ]; then
                 echo "Only one of --staging or --frozen is allowed"
@@ -77,7 +101,7 @@ while [ "$1" ]; do
             fi
             FILE_AREA="$1"
             ;;
-        "--check-timestamps")
+        "--timestamps")
             CHECK_TIMESTAMPS="$1"
             ;;
         "--report" | "--report-errors")
@@ -107,6 +131,11 @@ if [ "$REPORT_REQ" != "" ]; then
     fi
 fi
 
+# If date(time) not specified, use the unix epoch
+if [ "$SINCE" = "" ]; then
+    SINCE="1970-01-01T00:00:00Z"
+fi
+
 AUDIT_ARGS="${FILE_AREA} ${CHECK_TIMESTAMPS}"
 
 #--------------------------------------------------------------------------------
@@ -115,6 +144,7 @@ if [ "$DEBUG" = "true" ]; then
     echo "ROOT:       $ROOT"
     echo "PROJECT:    $PROJECT"
     echo "START:      $START"
+    echo "SINCE:      $SINCE"
     echo "AUDIT_ARGS: $AUDIT_ARGS"
     echo "REPORT_REQ: $REPORT_REQ"
     echo "RECIPIENTS: $RECIPIENTS"
@@ -134,30 +164,37 @@ REPORT_BASE="${LOG_ROOT}/audits/${YEAR}/${MONTH}/${START}_${PROJECT}"
 
 mkdir -p $REPORT_ROOT/$YEAR/$MONTH 2>/dev/null
 
+#--------------------------------------------------------------------------------
+
+OUTPUT="/tmp/$$.out"
+SUMMARY="$OUTPUT.summary"
+
 source $ROOT/venv/bin/activate
 
-python -u $ROOT/utils/admin/lib/audit-project.py $ROOT $PROJECT $START $AUDIT_ARGS > $$.out
+python -u $ROOT/utils/admin/lib/audit-project.py $ROOT $PROJECT $START $SINCE $AUDIT_ARGS > $OUTPUT
 
 if [ $? -ne 0 ]; then
-    rm $$.out 2>/dev/null
+    rm $OUTPUT 2>/dev/null
     errorExit "Auditing of project $PROJECT failed"
 fi
 
-cat $$.out | jq --indent 4 > $REPORT_BASE
+if [ $(stat -c %s "$OUTPUT") -eq 0 ]; then
+    cat $OUTPUT > $REPORT_BASE
+else
+    cat $OUTPUT | jq --indent 4 > $REPORT_BASE
+fi
 
 if [ $? -ne 0 ]; then
     if [ -f $REPORT_BASE ]; then
         if [ -s $REPORT_BASE ]; then
-            mv $$.out $REPORT_BASE.err
+            mv $OUTPUT $REPORT_BASE.err
         else
             mv $REPORT_BASE $REPORT_BASE.err
         fi
     fi
-    rm $$.out 2>/dev/null
+    rm $OUTPUT 2>/dev/null
     errorExit "Formatting of auditing report for project $PROJECT failed"
 fi
-
-rm $$.out 2>/dev/null
 
 SEND_REPORT="false"
 
@@ -174,9 +211,9 @@ else
 fi
 
 if [ "$OK" = "true" ]; then
-    REPORT="$REPORT_BASE.ok"
+    REPORT="$REPORT_BASE.OK.json"
 else
-    REPORT="$REPORT_BASE.err"
+    REPORT="$REPORT_BASE.ERR.json"
     if [ "$REPORT_REQ" = "--report-errors" ]; then
         SEND_REPORT="true"
     fi
@@ -186,11 +223,9 @@ mv $REPORT_BASE $REPORT
 
 echo "Audit results saved to file $REPORT" 
 
-if [ "$OK" = "false" ]; then
-    $ROOT/utils/admin/analyze-audit-errors "$REPORT"
-    if [ $? -ne 0 ]; then
-        errorExit "Analysis of audit error report $REPORT failed"
-    fi
+jq 'del(.invalidNodes, .errors)' --indent 4 < $OUTPUT > $SUMMARY
+if [ $? -ne 0 ]; then
+    errorExit "Generation of auditing report summary $REPORT failed"
 fi
 
 # Send email if specified
@@ -212,15 +247,18 @@ if [ "$SEND_REPORT" = "true" ] && [ "$RECIPIENTS" != "" ]; then
         SUBJECT="${IDA_ENVIRONMENT} (${HOSTNAME}) ${SUBJECT}"
     fi
 
-    if [ "$OK" ]; then
+    if [ "$OK" = "true" ]; then
         SUBJECT="${SUBJECT} - OK"
-        MESSAGE_FILE="$REPORT"
     else
         SUBJECT="${SUBJECT} - Errors Reported"
-        MESSAGE_FILE="$REPORT.analysis.summary"
     fi
 
-    cat "$MESSAGE_FILE" | mail -s "$SUBJECT" -r $EMAIL_SENDER $RECIPIENTS 
+    cat "$SUMMARY" | mail -s "$SUBJECT" -r $EMAIL_SENDER $RECIPIENTS 
 fi
+
+cat $SUMMARY
+
+rm $OUTPUT 2>/dev/null
+rm $SUMMARY 2>/dev/null
 
 addToLog "DONE"
diff --git a/utils/admin/list-active-projects b/utils/admin/list-active-projects
--- a/utils/admin/list-active-projects
+++ b/utils/admin/list-active-projects
@@ -32,10 +32,10 @@
 SCRIPT=`basename "$(realpath $0)"`
 
 USAGE="
-Usage: $SCRIPT [ ( timestamp | week | month | year ) ] 
+Usage: $SCRIPT [ ( date[time] | week | month | year ) ] 
        $SCRIPT -h
 
-       timestamp    an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/ (defaults to 24 hours ago)
+       date[time]   an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/ (defaults to 24 hours ago)
        week         calculate a timestamp one week in the past
        month        calculate a timestamp one month in the past
        year         calculate a timestamp one year in the past
@@ -56,30 +56,24 @@ else
     exit 1
 fi
 
+#DEBUG="true" # TEMP HACK
+
 #--------------------------------------------------------------------------------
 
 TZ=UTC
 
 SINCE=""
 
-# If relative period specified, calculate accordingly
-if [[ "$1" =~ ^(week|month|year)$ ]]; then
-    SINCE=`date -d "$START - 1 $1" +"%Y-%m-%dT%H:%M:%SZ"`
-fi
-
-# If date(time) is specified, ensure it is valid
-if [ "$SINCE" = "" ]; then
-    if [ "$1" != "" ]; then
-        if [[ ! "$1" =~ ^[12][0-9]{3}-[01][0-9]-[0-3][0-9]T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]]; then
-            # If only date specified, add default time component for beginning of that day.
-            if [[ "$1" =~ ^[12][0-9]{3}-[01][0-9]-[0-3][0-9]$ ]]; then
-                SINCE="${1}T00:00:00Z"
-            else
-                errorExit "Invalid timestamp: $1"
-            fi
-        else
-            SINCE="$1"
-        fi
+if [ "$1" ]; then
+    if [[ "$1" =~ ^(week|month|year)$ ]]; then
+        SINCE=`date -d "$START - 1 $1" +"%Y-%m-%dT%H:%M:%SZ"`
+    elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
+        SINCE="$1"
+    elif [[ "$1" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
+        SINCE="$1""T00:00:00Z"
+    else
+        echo "Invalid date[time]: $1"
+        exit 1
     fi
 fi
 
@@ -87,8 +81,6 @@ fi
 if [ "$SINCE" = "" ]; then
     SINCE=`date -d "$START - 24 hours" +"%Y-%m-%dT%H:%M:%SZ"`
 fi
-
-#DEBUG="true" # TEMP HACK
 
 if [ "$DEBUG" = "true" ]; then
     echo "SINCE: $SINCE"
@@ -101,7 +93,7 @@ fi
 
 source $ROOT/venv/bin/activate
 
-python -u $ROOT/utils/admin/lib/list-active-projects.py $ROOT $SINCE $START
+python -u $ROOT/utils/admin/lib/list-active-projects.py $ROOT $SINCE
 
 if [ $? -ne 0 ]; then
     errorExit "Failed to retrieve listing of active projects"
